#!/bin/bash --login
set -e
cd $(dirname $0)/../..

. _CI/scripts/bootstrap

rm -rf build dist

# we want all these files to exist in the actual package
cp .VERSION emaillib/.VERSION
cp LICENSE emaillib/LICENSE
cp AUTHORS.rst emaillib/AUTHORS.rst
cp CONTRIBUTING.rst emaillib/CONTRIBUTING.rst
cp HISTORY.rst emaillib/HISTORY.rst
cp README.rst emaillib/README.rst
cp USAGE.rst emaillib/USAGE.rst

python setup.py sdist bdist_egg

rm emaillib/.VERSION
rm emaillib/LICENSE
rm emaillib/AUTHORS.rst
rm emaillib/CONTRIBUTING.rst
rm emaillib/HISTORY.rst
rm emaillib/README.rst
rm emaillib/USAGE.rst
